name: kingdomino_score_count
description: Kingdomino board game score calculation

version: 3.0.1+20

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^4.0.1
  flutter_svg: ^2.0.6
  flutter_bloc: ^8.0.0
  replay_bloc: ^0.2.0
  provider: ^6.0.0
  equatable: ^2.0.0
  charcode: ^1.3.1
  
dev_dependencies:
  test: ^1.24.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quests/
    - assets/lacour/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
