name: kingdomino_score_count
description: Kingdomino board game score calculation

version: 3.2.3+25

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.0
  replay_bloc: ^0.2.0
  equatable: ^2.0.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  
dev_dependencies:
  test: ^1.25.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quests/
    - assets/lacour/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
