name: kingdomino_score_count
description: Kingdomino board game score calculation

version: 3.0.0+19

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  package_info_plus: ^1.4.0
  flutter_svg: ^1.0.0
  badges: ^2.0.0
  flutter_bloc: ^8.0.0
  replay_bloc: ^0.2.0
  
dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/quests/
    - assets/lacour/
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  fonts:
    - family: HammersmithOne
      fonts:
        - asset: fonts/HammersmithOne-Regular.ttf
